baseurl = "https://www.islandviewpta.org"
languageCode = "en-us"
title = "Island View Elementary PTA"
navigateToChanged = true
metaDataFormat = "yaml"
enableEmoji = true

[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = false
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

[params.cloudinary]
  cloud_name = "ivepta"
  use_upload = false
[params.cloudinary.lazysizes]
  enabled = true
[params.cloudinary.presets.default]
  max_width = 1920
  min_width = 320
  quality = 80
  sizes = "auto"
  steps = 10
  width = 450

[params]
  contact = "webadmin@islandviewpta.org" # Optional
  sitetitle = "Island View Elementary PTA"
  dateformat = "Jan 2, 2006" # Optional
  googleAnalytics = "UA-105410484-1" # Optional

[social]
  twitter = "ivepta"
  facebook = "IslandViewPTA"