baseurl = "https://www.islandviewpta.org"
languageCode = "en-us"
title = "Island View Elementary PTA"
navigateToChanged = true
metaDataFormat = "yaml"
enableEmoji = true

[build]
writeStats = true

[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = false
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

[params]
  contact = "webadmin@islandviewpta.org" # Optional
  sitetitle = "Island View Elementary PTA"
  dateformat = "Jan 2, 2006" # Optional
  googleAnalytics = "UA-105410484-1" # Optional

[social]
  twitter = "ivepta"
  facebook = "IslandViewPTA"