[build]
  command = "python src/scripts/gspread2md.py && npm run build"
  publish = "dist"
  HUGO_VERSION = "0.38.1"

[context.deploy-preview]
  command = "npm run build-preview"
  HUGO_VERSION = "0.38.1"
