---
upload_path: "/site/static/uploads/"
frontmatter_file_url_template: "/uploads/"
body_file_url_template: "/uploads/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: '0.26'
