---
new_page_extension: md
auto_deploy: false
admin_path: "/editor/"
webhook_url: 
sections: 
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
