baseurl = "/"
languageCode = "en-us"
title = "Homepage"
navigateToChanged = true

[params]
  contact = "webadmin@islandviewpta.org" # Optional
  sitetitle = "Island View Elementary PTA"
  dateformat = "Jan 2, 2006" # Optional
  googleAnalytics = "UA-XXXXXXXX-XX" # Optional
  googlefonts = "https://fonts.googleapis.com/css?family=Nunito+Sans:400,700" # Optional, Include google fonts.

[social]
  twitter = "ivepta"
  facebook = ""