baseurl = "https://www.islandviewpta.org"
languageCode = "en-us"
title = "Island View Elementary PTA"
navigateToChanged = true
metaDataFormat = "yaml"

[blackfriday]
  hrefTargetBlank = true

[params]
  contact = "webadmin@islandviewpta.org" # Optional
  sitetitle = "Island View Elementary PTA"
  dateformat = "Jan 2, 2006" # Optional
  googleAnalytics = "UA-105410484-1" # Optional

[social]
  twitter = "ivepta"
  facebook = ""

[outputFormats.EventsJSON]
  mediaType = "application/json"
  baseName = "events"
  isPlainText = true