---
new_page_extension: md
auto_deploy: false
admin_path: "/static/editor"
webhook_url: 
sections:
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: document
  path: content/movie.md
  label: Movie
- type: document
  path: content/yearbook/_index.md
  label: Yearbook
- type: document
  path: content/colorrun/_index.md
  label: Color Run
- type: document
  path: content/wishlist.md
  label: Wishlist
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
