---
new_page_extension: md
auto_deploy: false
admin_path: "/static/editor"
webhook_url: 
sections:
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: document
  path: content/movie.md
  label: Movie
- type: document
  path: content/yearbook/_index.md
  label: Yearbook
- type: document
  path: content/colorrun/_index.md
  label: Color Run
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.54.0
